// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin/applications" | "/admin/dashboard" | "/admin/job-seekers" | "/admin/jobs" | "/admin/jobs/add" | "/admin/jobs/edit/[id]" | "/admin/jobs/view/[id]" | "/admin/profile" | "/admin/users" | "/contact" | "/employer/applications" | "/employer/applications/[jobId]" | "/employer/dashboard" | "/employer/job-seekers" | "/employer/jobs" | "/employer/post-job" | "/employer/profile" | "/jobs" | "/login" | "/register" | "/seeker/dashboard" | "/seeker/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/employer"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/applications": {}
  "/admin/dashboard": {}
  "/admin/job-seekers": {}
  "/admin/jobs": {}
  "/admin/jobs/add": {}
  "/admin/jobs/edit/[id]": { "id": string; }
  "/admin/jobs/view/[id]": { "id": string; }
  "/admin/profile": {}
  "/admin/users": {}
  "/contact": {}
  "/employer": {}
  "/employer/applications": {}
  "/employer/applications/[jobId]": { "jobId": string; }
  "/employer/dashboard": {}
  "/employer/job-seekers": {}
  "/employer/jobs": {}
  "/employer/post-job": {}
  "/employer/profile": {}
  "/jobs": {}
  "/login": {}
  "/register": {}
  "/seeker/dashboard": {}
  "/seeker/profile": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/employer": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
